# ************************************************************************* #
#                                                                           #
#                                                      :::      ::::::::    #
#  level_generator.py                                :+:      :+:    :+:    #
#                                                  +:+ +:+         +:+      #
#  By: nramalan <nramalan@student.42antananari   +#+  +:+       +#+         #
#                                              +#+#+#+#+#+   +#+            #
#  Created: 2026/05/27 17:33:57 by nramalan        #+#    #+#               #
#  Updated: 2026/07/10 20:32:02 by nramalan        ###   ########.fr        #
#                                                                           #
# ************************************************************************* #

import random
from typing import List, Set, Tuple

from src.model import GameConfig, SimplePacgum, SuperPacgum
from src.model.game_context import LevelData

# from mazegenerator import MazeGenerator


class LevelGenerator:
    def __init__(self, config: GameConfig) -> None:
        self.config = config

    def _generate_pacgums(
        self,
        maze: List[List[int]],
        num_pacgums: int,
        min_distance_tiles: int = 2,
    ) -> Tuple[List[SuperPacgum], List[SimplePacgum]]:
        """
        Generates instances of SimplePacgum and SuperPacgum for a maze.
        PRIORITY 1: Corridor positions with strict distance spacing
        PRIORITY 2: Fill remaining target using remaining corridors
        PRIORITY 3: Force target match using completely random
                    positions if maze is too small
        Parameters:
        - maze: 2D list where 0 represents a corridor and 1 represents a wall.
        - num_pacgums: The target number of regular pacgums to place.
        - min_distance_tiles: Minimum grid distance between regular pacgums.

        Returns:
        - super_pacgums_list: A list of SuperPacgum instances.
        - simple_pacgums_list: A list of SimplePacgum instances.
        """

        rows = len(maze)
        cols = len(maze[0])

        corridors = [
            (r, c) for r in range(rows) for c in range(cols) if maze[r][c] == 0
        ]

        if not corridors:
            return [], []

        chosen_super_spots: Set[Tuple[int, int]] = set()
        corners = [(0, 0), (0, cols - 1), (rows - 1, 0), (rows - 1, cols - 1)]
        for corner in corners:
            chosen_super_spots.add(corner)

        available_slots = [p for p in corridors if p not in chosen_super_spots]
        random.shuffle(available_slots)

        chosen_simple_spots: Set[Tuple[int, int]] = set()

        def is_well_separated(pos, existing_spots, dist_threshold):
            for ep in existing_spots:
                if abs(pos[0] - ep[0]) + abs(pos[1] - ep[1]) < dist_threshold:
                    return False
            return True

        for slot in available_slots:
            if len(chosen_simple_spots) >= num_pacgums:
                break
            if is_well_separated(
                slot, chosen_simple_spots, min_distance_tiles
            ):
                chosen_simple_spots.add(slot)

        if len(chosen_simple_spots) < num_pacgums:
            for slot in available_slots:
                if len(chosen_simple_spots) >= num_pacgums:
                    break
                if slot not in chosen_simple_spots:
                    chosen_simple_spots.add(slot)

        if len(chosen_simple_spots) < num_pacgums:
            all_possible_grid_slots = [
                (r, c)
                for r in range(rows)
                for c in range(cols)
                if (r, c) not in chosen_super_spots
            ]
            random.shuffle(all_possible_grid_slots)

            for slot in all_possible_grid_slots:
                if len(chosen_simple_spots) >= num_pacgums:
                    break
                if slot not in chosen_simple_spots:
                    chosen_simple_spots.add(slot)

        super_pacgums_list = [
            SuperPacgum(c, r) for (r, c) in chosen_super_spots
        ]
        simple_pacgums_list = [
            SimplePacgum(c, r) for (r, c) in chosen_simple_spots
        ]
        return super_pacgums_list, simple_pacgums_list

    def generate_levels(self) -> List[LevelData]:
        levels: List[LevelData] = []
        for _, lvl in enumerate(self.config.levels):
            print(f"level {lvl.model_dump_json()}")
            maze = self._generate_maze(lvl.width, lvl.height)
            levels.append(
                LevelData(
                    width=lvl.width,
                    height=lvl.height,
                    maze_data=maze,
                    pacgums=self._generate_pacgums(maze, 100, 2),
                )
            )
        return levels

    def _generate_maze(self, width, height) -> List[List[int]]:
        # gen = MazeGenerator(
        # size=(lvl.width, lvl.height), perfect=False,
        # entry_cell=(0, 0),
        # exit_cell=(lvl.width - 1, lvl.height - 1),
        # seed=self.config.seed
        # )
        # gen.generate()
        # print(gen.maze)
        maze = [
            [
                11,
                11,
                13,
                5,
                3,
                11,
                13,
                5,
                5,
                5,
                1,
                3,
                11,
                11,
                13,
                5,
                3,
                13,
                5,
                3,
                11,
                11,
                11,
                13,
                3,
                11,
                11,
                11,
                11,
                9,
                5,
                7,
                11,
                9,
                3,
            ],
            [
                10,
                8,
                5,
                3,
                12,
                2,
                13,
                1,
                7,
                9,
                6,
                10,
                10,
                10,
                11,
                13,
                4,
                5,
                5,
                2,
                10,
                8,
                0,
                3,
                10,
                12,
                4,
                4,
                2,
                12,
                3,
                13,
                4,
                2,
                14,
            ],
            [
                10,
                14,
                9,
                4,
                5,
                4,
                1,
                4,
                1,
                0,
                7,
                12,
                0,
                0,
                4,
                1,
                5,
                5,
                5,
                4,
                0,
                2,
                14,
                8,
                4,
                5,
                5,
                5,
                0,
                5,
                6,
                11,
                9,
                4,
                7,
            ],
            [
                8,
                1,
                4,
                7,
                13,
                5,
                6,
                9,
                6,
                10,
                13,
                1,
                6,
                10,
                13,
                2,
                13,
                3,
                9,
                3,
                14,
                10,
                9,
                2,
                9,
                5,
                1,
                1,
                0,
                7,
                9,
                4,
                0,
                1,
                7,
            ],
            [
                14,
                14,
                13,
                1,
                5,
                3,
                9,
                0,
                7,
                10,
                13,
                0,
                3,
                12,
                3,
                14,
                13,
                0,
                2,
                12,
                5,
                2,
                10,
                14,
                14,
                13,
                6,
                14,
                8,
                7,
                8,
                7,
                14,
                10,
                11,
            ],
            [
                11,
                13,
                5,
                6,
                13,
                4,
                2,
                8,
                3,
                14,
                13,
                2,
                12,
                7,
                14,
                9,
                1,
                6,
                14,
                13,
                5,
                2,
                14,
                13,
                3,
                13,
                5,
                3,
                8,
                7,
                8,
                3,
                13,
                0,
                2,
            ],
            [
                8,
                5,
                5,
                5,
                5,
                1,
                2,
                10,
                12,
                7,
                11,
                14,
                13,
                5,
                5,
                6,
                12,
                7,
                11,
                13,
                1,
                6,
                13,
                1,
                4,
                5,
                1,
                4,
                4,
                1,
                6,
                14,
                9,
                6,
                14,
            ],
            [
                14,
                9,
                3,
                9,
                1,
                6,
                10,
                14,
                13,
                5,
                0,
                7,
                13,
                3,
                11,
                13,
                1,
                7,
                8,
                1,
                6,
                13,
                1,
                4,
                7,
                11,
                14,
                11,
                13,
                0,
                1,
                7,
                8,
                5,
                7,
            ],
            [
                11,
                14,
                8,
                2,
                14,
                9,
                0,
                5,
                7,
                13,
                0,
                3,
                13,
                2,
                12,
                1,
                0,
                3,
                14,
                14,
                11,
                11,
                12,
                7,
                11,
                8,
                5,
                0,
                5,
                2,
                12,
                3,
                8,
                1,
                7,
            ],
            [
                8,
                5,
                6,
                12,
                7,
                10,
                14,
                13,
                1,
                3,
                14,
                8,
                1,
                4,
                1,
                2,
                14,
                10,
                13,
                3,
                12,
                0,
                1,
                5,
                0,
                2,
                13,
                2,
                9,
                0,
                3,
                14,
                10,
                8,
                7,
            ],
            [
                14,
                13,
                5,
                1,
                1,
                4,
                1,
                7,
                14,
                12,
                1,
                6,
                8,
                3,
                14,
                14,
                13,
                4,
                5,
                0,
                1,
                6,
                10,
                13,
                6,
                10,
                13,
                6,
                10,
                10,
                12,
                7,
                14,
                14,
                11,
            ],
            [
                9,
                1,
                5,
                6,
                14,
                13,
                6,
                9,
                7,
                13,
                2,
                13,
                6,
                14,
                13,
                5,
                3,
                13,
                5,
                2,
                10,
                13,
                6,
                9,
                1,
                4,
                5,
                7,
                10,
                8,
                5,
                1,
                1,
                7,
                10,
            ],
            [
                14,
                14,
                9,
                5,
                3,
                9,
                1,
                0,
                5,
                5,
                2,
                13,
                1,
                1,
                1,
                1,
                0,
                1,
                1,
                6,
                14,
                11,
                13,
                2,
                14,
                9,
                5,
                3,
                14,
                8,
                3,
                10,
                8,
                5,
                2,
            ],
            [
                13,
                5,
                6,
                9,
                4,
                2,
                14,
                10,
                9,
                5,
                2,
                13,
                6,
                14,
                10,
                10,
                10,
                10,
                10,
                11,
                9,
                4,
                5,
                2,
                9,
                4,
                7,
                12,
                1,
                2,
                14,
                10,
                12,
                7,
                10,
            ],
            [
                13,
                5,
                5,
                0,
                7,
                14,
                13,
                6,
                14,
                13,
                4,
                3,
                11,
                13,
                6,
                10,
                10,
                14,
                10,
                8,
                6,
                13,
                5,
                6,
                14,
                9,
                1,
                1,
                2,
                8,
                3,
                14,
                13,
                5,
                2,
            ],
            [
                9,
                1,
                5,
                2,
                13,
                3,
                13,
                1,
                3,
                13,
                3,
                14,
                12,
                1,
                5,
                6,
                10,
                13,
                2,
                10,
                13,
                5,
                1,
                1,
                5,
                2,
                14,
                14,
                10,
                10,
                8,
                7,
                9,
                5,
                6,
            ],
            [
                10,
                14,
                13,
                4,
                7,
                12,
                3,
                10,
                8,
                1,
                0,
                5,
                1,
                2,
                11,
                11,
                14,
                9,
                6,
                10,
                13,
                1,
                6,
                10,
                9,
                6,
                11,
                11,
                14,
                14,
                8,
                7,
                8,
                5,
                7,
            ],
            [
                10,
                11,
                11,
                9,
                1,
                5,
                0,
                2,
                10,
                10,
                8,
                7,
                14,
                14,
                8,
                0,
                5,
                0,
                7,
                14,
                13,
                6,
                11,
                10,
                8,
                7,
                8,
                0,
                1,
                1,
                2,
                11,
                12,
                1,
                3,
            ],
            [
                12,
                6,
                8,
                2,
                8,
                3,
                10,
                14,
                10,
                14,
                12,
                7,
                11,
                9,
                2,
                10,
                9,
                2,
                9,
                5,
                5,
                1,
                4,
                2,
                8,
                7,
                10,
                10,
                14,
                10,
                8,
                2,
                13,
                2,
                10,
            ],
            [
                13,
                1,
                2,
                14,
                10,
                14,
                8,
                7,
                8,
                1,
                3,
                13,
                2,
                14,
                10,
                14,
                14,
                10,
                14,
                13,
                5,
                2,
                11,
                10,
                14,
                9,
                2,
                10,
                9,
                2,
                10,
                12,
                7,
                10,
                10,
            ],
            [
                13,
                2,
                10,
                11,
                14,
                13,
                2,
                11,
                10,
                14,
                12,
                7,
                12,
                5,
                0,
                7,
                11,
                8,
                3,
                9,
                3,
                14,
                8,
                2,
                11,
                14,
                10,
                10,
                10,
                14,
                12,
                3,
                13,
                2,
                10,
            ],
            [
                13,
                6,
                14,
                12,
                5,
                5,
                4,
                6,
                14,
                13,
                5,
                5,
                5,
                5,
                4,
                7,
                12,
                6,
                14,
                14,
                12,
                5,
                6,
                12,
                4,
                7,
                14,
                14,
                14,
                13,
                5,
                6,
                13,
                6,
                14,
            ],
        ]
        return maze
