from enum import StrEnum


class PageState(StrEnum):
    LOADING_PAGE = "LOADING_PAGE"
    MAIN_MENU = "MAIN_MENU"
    HELP_MENU = "HELP_MENU"
    GAME_PAGE = "GAME_PAGE"
    PLAYER_NAME_PAGE = "PLAYER_NAME_PAGE"
    HIGH_SCORES_PAGE = "HIGH_SCORES_PAGE"
